### ISSUE TITLE
ASM: 'network route-table route set' not working for next-hop-type "VirtualAppliance" 

### ISSUE THREAD

**Issue by HimanshuBri** [MSOpenTech/azure-xplat-cli#260]
Have attached the screenshot for the same.
 
![image](https://cloud.githubusercontent.com/assets/10084788/7981063/07fc9032-0aca-11e5-8e92-3aae13888f20.png)

**Comment by romangromov** [comment]
@HimanshuBri known issue, external, reported to @anuchandy, stay tuned, thank you

**Comment by romangromov** [comment]
Attaching  full http request/response here https://gist.github.com/romangromov/5a058e7e44cb6344c945#file-asm-route-table-set

**Comment by romangromov** [comment]
Attaching full http request/response herehttps://gist.github.com/romangromov/d35ca5dae9bd7dd30ec7#file-asm-route-table-set-type

**Comment by romangromov** [comment]
@sreekanthbs should be fixed now, please checkout `asm-network-fixes` branch

**Comment by sreekanthbs** [comment]
@romangromov still not working.
![image](https://cloud.githubusercontent.com/assets/11171941/9355569/04e54736-4698-11e5-9769-8c25ef3c5697.png)

Spelling mistake in help
![image](https://cloud.githubusercontent.com/assets/11171941/9355650/8d0757ee-4698-11e5-994d-348a9d565f4e.png)

**Comment by romangromov** [comment]
@sreekanthbs thanks, give it another chance please - should be fixed

**Comment by sreekanthbs** [comment]
@romangromov It is working fine. spell issue still there.
![image](https://cloud.githubusercontent.com/assets/11171941/9357070/77a7b876-46a2-11e5-88a0-d0f395e1fe6e.png)

**Comment by romangromov** [comment]
@sreekanthbs oh sorry, my bad. spell issue fixed as well now

**Comment by babumuralidharan** [comment]
LGTM :+1:
