### ISSUE TITLE
ASM: 'network subnet create' giving error

### ISSUE THREAD

**Issue by HimanshuBri** [MSOpenTech/azure-xplat-cli#285]
Please find the attached screenshot.
![image](https://cloud.githubusercontent.com/assets/10084788/8030621/e77d26ae-0de5-11e5-9bed-fa0c7c9fbb60.png)

**Comment by MikhailTryakhov** [comment]
@HimanshuBri thank you, could you please try to use "10.0.0.0/8" address prefix in create command?
Will it unblock you?

**Comment by romangromov** [comment]
@HimanshuBri looks like used `subnet address space` is not valid in `vnet address space`. Please, try use another one `address prefix for subne`t and make sure it's valid on `vnet address space` range.

**Comment by HimanshuBri** [comment]
@MikhailTryakhov @romangromov. I feel there is some other error.
Have at look at the screenshot.
![image](https://cloud.githubusercontent.com/assets/10084788/8031646/cc1ab068-0ded-11e5-8273-2b7c954039b3.png)

**Comment by HimanshuBri** [comment]
@romangromov. Any updates on this.

**Comment by MikhailTryakhov** [comment]
@HimanshuBri We have found that subnet name is always the same - Subnet-1 instead of cli-provided name, this looks like a server side issue

**Comment by MikhailTryakhov** [comment]
Adding @anuchandy to confirm it's external

**Comment by MikhailTryakhov** [comment]
Attaching full http request/response: https://gist.github.com/MikhailTryakhov/0d00525dc1f075d54803

**Comment by anuchandy** [comment]
@HimanshuBri here we are overlapping the IP address range. i.e. the subnet range for subnet-1 and subnet-4 is overlapping. We have already reported this to network team.

**Comment by romangromov** [comment]
Hi @sreekanthbs, please make sure `Subnet-1` issue (wrong Subnet name issue) is fixed now

**Comment by sreekanthbs** [comment]
@romangromov  i verified in asm-network-fixes .
The issue is still reproducible
![image](https://cloud.githubusercontent.com/assets/11171941/9460886/a31f336a-4b27-11e5-8015-faba5ca08045.png)

**Comment by romangromov** [comment]
@sreekanthbs thank you for update

**Comment by MikhailTryakhov** [comment]
Issue still exists
