### ISSUE TITLE
ASM: cannot add more then one frontend-ip to an application gateway config

### ISSUE THREAD

**Issue by romangromov** [MSOpenTech/azure-xplat-cli#293]
Comment from Kapil Garg <kaga@microsoft.com>:

`
ASM doesn’t support one cloud service having more than one private end point. Hence application gateway supports only one FrontendIP configuration. 
`

Attaching full http request/response: https://gist.github.com/romangromov/dad66aa2cabfccf1489a#file-asm-app-gateway-frontendip-add

**Comment by MikhailTryakhov** [comment]
Same for the 'frontend-ip remove' command

**Comment by romangromov** [comment]
@sreekanthbs this should be fixed now, please use `asm-network-fixes` branch

**Comment by sreekanthbs** [comment]
@romangromov Issue still exist
![image](https://cloud.githubusercontent.com/assets/11171941/9461467/834ac8b0-4b2c-11e5-8726-1cd444d24810.png)

**Comment by sreekanthbs** [comment]
@romangromov issue still exist
![image](https://cloud.githubusercontent.com/assets/11171941/9464086/bad723c0-4b3e-11e5-9664-fae3c776a6fe.png)

**Comment by romangromov** [comment]
@sreekanthbs Thank! please, give another chance for this, fixed now

**Comment by sreekanthbs** [comment]
It is working fine now. Can able to add more than one frontend-ip to an application gateway config
<pre>
<code>
root@DndLinuxVM:/home/azureuser/azure-xplat-cli-dev# node bin/azure network application-gateway frontend-ip add appgtwy1s frontendip2                     -i 10.0.2.0
info:    Executing command network application-gateway frontend-ip add
warn:    Using default type: Private
+ Getting configuration for an Application Gateway "appgtwy1s"
+ Setting configuration for an Application Gateway "appgtwy1s"
info:    network application-gateway frontend-ip add command OK
root@DndLinuxVM:/home/azureuser/azure-xplat-cli-dev# node bin/azure network application-gateway config show appgtwy1s                                    info:    Executing command network application-gateway config show
+ Getting configuration for an Application Gateway "appgtwy1s"
data:    Frontend IP configurations:
data:      Name                          : frontendip1
data:      Type                          : Private
data:      Static IP address             : 10.0.1.0
data:
data:      Name                          : frontendip2
data:      Type                          : Private
data:      Static IP address             : 10.0.2.0
data:
data:    Backend address pools:
data:      Name                          : pool1
data:      Backend servers:
data:        IP address                  : 10.0.0.1
data:
data:      Name                          : MyPool
data:      Backend servers:
data:        IP address                  : 10.0.0.2
data:
data:      Name                          : clitestaddpool
data:      Backend servers:
data:        IP address                  : 10.0.0.10
data:
data:    Http settings:
data:      Name                          : setting1
data:      Port                          : 80
data:      Protocol                      : Http
data:      Cookie based affinity         : Enabled
data:
data:      Name                          : MySettings
data:      Port                          : 81
data:      Protocol                      : Http
data:      Cookie based affinity         : Enabled
data:
data:      Name                          : settings2
data:      Port                          : 888
data:      Protocol                      : Http
data:      Cookie based affinity         : Disabled
data:
data:      Name                          : settings3
data:      Port                          : 999
data:      Protocol                      : Http
data:      Cookie based affinity         : Disabled
data:
data:    Frontend ports:
data:      Name                          : fep1
data:      Port                          : 80
data:
data:      Name                          : frontendport1
data:      Port                          : 80
data:
data:    Http listeners:
data:      Name                          : listener1
data:      Frontend port                 : fep1
data:      Protocol                      : Http
data:
data:    Load balancing rules:
data:      Name                          : rule1
data:      Type                          : Basic
data:      Http settings                 : setting1
data:      Listener                      : listener1
data:      Backend address pool          : pool1
data:
info:    network application-gateway config show command OK

</code>
</pre>

**Comment by romangromov** [comment]
@sreekanthbs thanks, it's merged to upstream, closing issue
