### ISSUE TITLE
ASM: 'network vnet local-network add' giving wrong error message when specifying already added local-network

### ISSUE THREAD

**Issue by HimanshuBri** [MSOpenTech/azure-xplat-cli#312]
Please find the attached screenshot.
![image](https://cloud.githubusercontent.com/assets/10084788/8103983/bfe1d254-104a-11e5-84e2-4dd69a84e7f0.png)

**Comment by roman-boltunov** [comment]
@HimanshuBri this might be external, lets wait for @anuchandy to answer on it.

**Comment by anuchandy** [comment]
@roman-boltunov just confirming, are we doing any check to see the association already exists? 

is this check straight forward? for example simple checking of an array with name, if yes then lets do it. 

if it involves complex client side check (like subnet overlapping check) then we should rely on server.

**Comment by roman-boltunov** [comment]
@anuchandy thank you for clarification. 
@HimanshuBri it is fixed now. Please make sure it works fine.

**Comment by HimanshuBri** [comment]
@roman-boltunov  Still getting the same error
<pre>
<code>
C:\June\15june\azure-xplat-cli-dev-asm-network>node bin/azure network vnet local-network add -n CliTestVnet1176 -l CliTestLocNet28683
info:    Executing command network vnet local-network add
+ Getting network configuration
warn:    A subnet with name "GatewaySubnet" must exist in the virtual network in-order to associate a local network with the virtual network
+ Associating local network "CliTestLocNet28683" with a virtual network "CliTestVnet1176"
error:   The server encountered an internal error. Please retry the request.
info:    Error information has been recorded to C:\Users\sunil.kumar1\.azure\azure.err
error:   network vnet local-network add command failed


C:\June\15june\azure-xplat-cli-dev-asm-network>node bin/azure network vnet list
info:    Executing command network vnet list
+ Getting virtual networks
data:    Name                                      Location     AffinityGroup       State
data:    ----------------------------------------  -----------  ------------------  --------
data:    azure4linux                               West Europe                      Created
<b>data:    CliTestVnet1176                           West US                          Created</b>
data:    CliTestVnet14748                          West US                          Created
data:    CliTestVnet22406                          West US                          Created
data:    CliTestVnet2368                           West US                          Created
data:    CliTestVnet2894                           West US                          Created
data:    CliTestVnet29358                          West US                          Created
data:    CliTestVnet6244                           West US                          Created
data:    CliTestVnet7285                           West US                          Created
data:    Group armresgrpeastustest1 TestArmVMList  West US                          Created
data:    mynetwork                                 undefined    affinity1           Created
data:    ne@@wvnet$$%10                            undefined    NewAffinityGroup01  Creating
data:    newvnet$$%10                              undefined    NewAffinityGroup01  Creating
data:    testy                                     undefined    affinity1           Created
data:    Vnet                                      undefined    EastAsia            Created
data:    vnet2                                     West US                          Created
data:    Vnet28                                    West US                          Created
info:    network vnet list command OK

C:\June\15june\azure-xplat-cli-dev-asm-network>node bin/azure network local-network list
info:    Executing command network local-network list
+ Getting network configuration
data:    Name                Gateway address  Address space
data:    ------------------  ---------------  ---------------
data:    CliTestLocNet26870  200.200.200.200  10.2.0.0/16
<b>data:    CliTestLocNet28683  200.200.200.200  10.2.0.0/16</b>
data:    LocalNetwork        191.236.86.5     10.16.0.45/29
data:    Testlocnet          200.200.200.200  10.3.0.0/16
data:    Testlocnet1         undefined        10.3.0.0/16
data:    Testlocnet10        10.8.10.10       10.0.0.0/27
data:    Testlocnet13        10.20.10.20      10.0.0.0/19
data:    Testlocnet2         10.10.10.10      10.0.0.0/8, ...
data:    Testlocnet3         10.20.10.20      10.0.0.0/9
data:    Testlocnet4         10.10.10.10      10.0.0.0/8, ...
data:    Testlocnet5         10.10.10.10      10.0.0.0/8, ...
data:    Testlocnet6         0.69.96.5        10.0.0.0/9
data:    Testlocnet7         0.0.0.0          10.0.0.0/8
data:    vnet1lnet           100.100.100.100  10.1.0.0/16
data:    vnet2lnet           200.200.200.200  10.2.0.0/16
data:    Vpn                 10.32.0.0        10.16.0.0/27
info:    network local-network list command OK
</code>
</pre>
