### ISSUE TITLE
Arm:network  vnet create with option --dns-servers is coming under address prefix only

### ISSUE THREAD

**Issue by HimanshuBri** [MSOpenTech/azure-xplat-cli#375]
Arm network vnet create with option --dns-servers is coming under address prefix only.
 label should be relevant to  DNS servers IP addresses.
![vnet create_set problem in dns](https://cloud.githubusercontent.com/assets/10084788/8356133/0f99fdcc-1b71-11e5-9a58-123eb8eae5c4.PNG)

**Comment by roman-boltunov** [comment]
@HimanshuBri it's fixed now. Could you please make sure everything works as expected?

**Comment by sreekanthbs** [comment]
@roman-boltunov  Issue still exist
<pre>
<code>
C:\June\26june\azure-xplat-cli-dev-asm-network>azure network vnet create armresgrp26j vnet29 eastus -a 10.0.0.0/24,10.0.1.0/24 <b>-d 10.0.0.0</b>
info:    Executing command network vnet create
+ Looking up virtual network "vnet29"
+ Creating virtual network "vnet29"
+ Loading virtual network state
data:    Id                              : /subscriptions/bfb5e0bf-124b-4d0c-9352-7c0a9f4d9948/resourceGroups/armresgrp26j/providers/Microsoft.Network/virtualNetworks
/vnet29
data:    Name                            : vnet29
data:    Type                            : Microsoft.Network/virtualNetworks
data:    Location                        : eastus
data:    ProvisioningState               : Succeeded
data:    Address prefixes:
data:      10.0.0.0/24
data:      10.0.1.0/24
<b>data:    Address prefixes:
data:      10.0.0.0</b>
info:    network vnet create command OK
</code>
</pre>

**Comment by roman-boltunov** [comment]
@sreekanthbs could you please sync once more with dev-asm-network branch and retry?

**Comment by sreekanthbs** [comment]
@roman-boltunov i guess  issue is  still there i  verified on latest dev-asm-network branch but able to repro the issue.
<pre>
<code>
C:\June\29eve\azure-xplat-cli-dev-asm-network>azure network vnet create armresgrp29j vnet29 eastus -a 10.0.0.0/24,10.0.1.0/24 -d 10.0.0.0
info:    Executing command network vnet create
+ Looking up virtual network "vnet29"
+ Creating virtual network "vnet29"
+ Loading virtual network state
data:    Id                              : /subscriptions/bfb5e0bf-124b-4d0c-9352-7c0a9f4d9948/resourceGroups/armresgrp29j/providers/Microsoft.Network/virtualNetworks
/vnet29
data:    Name                            : vnet29
data:    Type                            : Microsoft.Network/virtualNetworks
data:    Location                        : eastus
data:    ProvisioningState               : Succeeded
data:    Address prefixes:
data:      10.0.0.0/24
data:      10.0.1.0/24
data:    Address prefixes:
data:      10.0.0.0
info:    network vnet create command OK

C:\June\29eve\azure-xplat-cli-dev-asm-network>azure network vnet set armresgrp29j vnet29 -d 10.0.1.0 -t location=south;priority=medium
info:    Executing command network vnet set
+ Looking up virtual network "vnet29"
+ Updating virtual network "vnet29"
+ Loading virtual network state
data:    Id                              : /subscriptions/bfb5e0bf-124b-4d0c-9352-7c0a9f4d9948/resourceGroups/armresgrp29j/providers/Microsoft.Network/virtualNetworks
/vnet29
data:    Name                            : vnet29
data:    Type                            : Microsoft.Network/virtualNetworks
data:    Location                        : eastus
data:    Tags                            : location=south;priority=medium
data:    ProvisioningState               : Succeeded
data:    Address prefixes:
data:      10.0.0.0/24
data:      10.0.1.0/24
data:    Address prefixes:
data:      10.0.0.0
data:      10.0.1.0
info:    network vnet set command OK

</code>
</pre>

**Comment by MikhailTryakhov** [comment]
Hi @sreekanthbs  unfortunately can't repro this issue - in this case throws error. Please review screenshot below
![vnet no error](https://cloud.githubusercontent.com/assets/3079588/8671891/8ac7fec6-2a31-11e5-903c-c04ae3047d59.png)

**Comment by sreekanthbs** [comment]
@MikhailTryakhov You are running in ASM mode, the issue is for ARM

**Comment by MikhailTryakhov** [comment]
Thank you @sreekanthbs, I was confused a bit of previous logs name (zure-xplat-cli-dev-asm-network). Thank you, can we close it?

**Comment by sreekanthbs** [comment]
@MikhailTryakhov we can close this

**Comment by MikhailTryakhov** [comment]
Thank you @sreekanthbs 
Could you please add me in skype (nickname is 'Perseptron_') - my account is still blocked in skype for business (Lync) and I can't communicate there.
