### ISSUE TITLE
ARM: network application-gateway ssl-add giving error

### ISSUE THREAD

**Issue by sreekanthbs** [MSOpenTech/azure-xplat-cli#501]
network application-gateway ssl-add giving error <b>'certificate does not have Private Key'</b> even after creating ssl cert.
1. Generate Private Key on the Server Running Apache + mod_ssl
openssl genrsa -des3 -out myPrivateKey.key 1024
2. Generate a Certificate Signing Request (CSR)
openssl req -new -key myPrivateKey.key -out myCert.csr
3. Generate a Self-Signed SSL Certificate
openssl x509 -req -days 365 -in myCert.csr -signkey myPrivateKey.key -out myCert.crt
<pre>
<code>
C:\Sep2015\21Sep\azure-xplat-cli-dev-arm-app-gateways>node bin/azure network application-gateway ssl-cert add test-trya-group2 appgw03 testCert -t C:\Share\cert
file\ssl\myCert.crt -p pswd
info:    Executing command network application-gateway ssl-cert add
+ Looking up an Application Gateway "appgw03"
+ Setting configuration for an Application Gateway "appgw03"
error:   Certificate /subscriptions/bfb5e0bf-124b-4d0c-9352-7c0a9f4d9948/resourceGroups/test-trya-group2/providers/Microsoft.Network/applicationGateways/appgw03
/sslCertificates/testCert does not have Private Key.
info:    Error information has been recorded to C:\Users\sreekanth.bandaru\.azure\azure.err
error:   network application-gateway ssl-cert add command failed
</code>
</pre>

**Comment by MikhailTryakhov** [comment]
Hi @sreekanthbs 
please review comment from Kapil:
Regarding SSL: You have  to specify pfx file while adding certificate. You are specifying .cer file and getting error.

Could you please review such command again

**Comment by sreekanthbs** [comment]
@MikhailTryakhov Still getting error
<pre>
<code>
C:\Sep2015\29Sep\azure-xplat-cli-dev-arm-app-gateways>node bin/azure network application-gateway ssl-cert add test-trya-group1 appgw021 testCert -t "C:\sshkey\m
ycert.pfx" -p 1234
info:    Executing command network application-gateway ssl-cert add
+ Looking up an Application Gateway "appgw021"
error:   certFile is not defined
info:    Error information has been recorded to C:\Users\sreekanth.bandaru\.azure\azure.err
error:   network application-gateway ssl-cert add command failed
</code>
</pre>
Here azure.err file
<pre>
<code>
Tue Sep 29 2015 19:27:57 GMT+0530 (India Standard Time):
{ [ReferenceError: certFile is not defined]
  __frame: 
   { name: 'addSsl__10',
     line: 278,
     file: 'C:\\Sep2015\\29Sep\\azure-xplat-cli-dev-arm-app-gateways\\lib\\commands\\arm\\network\\appGateway._js',
     prev: 
      { name: '__106',
        line: 2276,
        file: 'C:\\Sep2015\\29Sep\\azure-xplat-cli-dev-arm-app-gateways\\lib\\commands\\arm\\network\\network._js',
        prev: undefined,
        calls: 6,
        active: false,
        offset: 9,
        col: 17 },
     calls: 1,
     active: true,
     offset: 2,
     col: 26 },
  rawStack: [Getter] }
ReferenceError: certFile is not defined
    at ___ (C:\Sep2015\29Sep\azure-xplat-cli-dev-arm-app-gateways\lib\commands\arm\network\appGateway._js:558:39)
    at ___ (C:\Sep2015\29Sep\azure-xplat-cli-dev-arm-app-gateways\node_modules\streamline\lib\callbacks\runtime.js:111:13)
    at __$get__3 (C:\Sep2015\29Sep\azure-xplat-cli-dev-arm-app-gateways\lib\commands\arm\network\appGateway._js:231:18)
    at __tryCatch (C:\Sep2015\29Sep\azure-xplat-cli-dev-arm-app-gateways\node_modules\streamline\lib\callbacks\runtime.js:150:4)
    at ___ (C:\Sep2015\29Sep\azure-xplat-cli-dev-arm-app-gateways\lib\commands\arm\network\appGateway._js:230:9)
    at ___ (C:\Sep2015\29Sep\azure-xplat-cli-dev-arm-app-gateways\lib\commands\arm\network\appGateway._js:222:17)
    at __tryCatch (C:\Sep2015\29Sep\azure-xplat-cli-dev-arm-app-gateways\node_modules\streamline\lib\callbacks\runtime.js:150:4)
    at ___ (C:\Sep2015\29Sep\azure-xplat-cli-dev-arm-app-gateways\lib\commands\arm\network\appGateway._js:220:13)
    at __$get__3 (C:\Sep2015\29Sep\azure-xplat-cli-dev-arm-app-gateways\lib\commands\arm\network\appGateway._js:217:15)
    at __tryCatch (C:\Sep2015\29Sep\azure-xplat-cli-dev-arm-app-gateways\node_modules\streamline\lib\callbacks\runtime.js:150:4)
</code>
</pre>

**Comment by MikhailTryakhov** [comment]
Hi @sreekanthbs 
it's fixed now. Please test it again

**Comment by sreekanthbs** [comment]
Still throwing error
<pre>
<code>
C:\Sep2015\30Sep\azure-xplat-cli-dev-arm-app-gateways>node bin/azure network application-gateway ssl-cert add test-trya-group1 appgw021 testCert -f C:\sshkey\my
cert.pfx -p 12345
info:    Executing command network application-gateway ssl-cert add
+ Looking up an Application Gateway "appgw021"
+ Setting configuration for an Application Gateway "appgw021"
error:   Certificate /subscriptions/bfb5e0bf-124b-4d0c-9352-7c0a9f4d9948/resourceGroups/test-trya-group1/providers/Microsoft.Network/applicationGateways/appgw02
1/sslCertificates/testCert does not have Private Key.
info:    Error information has been recorded to C:\Users\sreekanth.bandaru\.azure\azure.err
error:   network application-gateway ssl-cert add command failed
</code>
</pre>

**Comment by MikhailTryakhov** [comment]
@sreekanthbs Please use [this](https://msdn.microsoft.com/en-us/library/ff699202.aspx) link to create pfx certificate and try to test command again.
It works correct on my side

**Comment by sreekanthbs** [comment]
@MikhailTryakhov  Its working fine now.Thanks for the link that really helped.
Closing the issue
<pre>
<code>
C:\Oct\9oct\azure-xplat-cli-dev-arm-app-gateways>node bin/azure network application-gateway ssl-cert add test-trya-group3 appgw03 -c SCSFTest -f C:\MakeCert\SCSFTest.
pfx -p Super@123
info:    Executing command network application-gateway ssl-cert add
+ Looking up an Application Gateway "appgw03"
+ Setting configuration for an Application Gateway "appgw03"
+ Looking up an Application Gateway "appgw03"
data:    Id                              : /subscriptions/bfb5e0bf-124b-4d0c-9352-7c0a9f4d9948/resourceGroups/test-trya-group3/providers/Microsoft.Network/application
Gateways/appgw03
data:    Name                            : appgw03
data:    Location                        : westus
data:    Provisioning state              : Succeeded
data:    Sku                             : Standard_Small
data:    Resource Group                  : test-trya-group3
data:    Gateway IP configations         : [gatewayip03]
data:    SSL cerificates                 : [SCSFTest]
data:    Frontend ip configurations      : [frontendip03]
data:    Frontend ports                  : [frontendport03, frntport3]
data:    Backend address pools           : [pool03, backendpool3]
data:    Backend http settings           : [setting03, httpsetting3]
data:    Http listeners                  : [listener03, httplistener3]
data:    Request routing rules           : [rule03]
data:    GatewayIpConfigurationText      : [
    {
        "subnet": {
            "id": "/subscriptions/bfb5e0bf-124b-4d0c-9352-7c0a9f4d9948/resourceGroups/test-trya-group3/providers/Microsoft.Network/virtualNetworks/tryaVnet3/subnets/t
estSubnet3"
        },
        "provisioningState": "Succeeded",
        "name": "gatewayip03",
        "etag": "W/\"eca6bc41-055a-4702-acfa-1dda7fb10fc3\"",
        "id": "/subscriptions/bfb5e0bf-124b-4d0c-9352-7c0a9f4d9948/resourceGroups/test-trya-group3/providers/Microsoft.Network/applicationGateways/appgw03/gatewayIPCo
nfigurations/gatewayip03"
    }
]
data:    SslCertificateText              : [
    {
        "publicCertData": "MIIB7jCCAVugAwIBAgIQeL/+xLwYN69BJTCFAOxF+jAJBgUrDgMCHQUAMBQxEjAQBgNVBAMTCVNDU0YgVGVzdDAeFw0xMzEyMzExODMwMDBaFw0xNTEyMzExODMwMDBaMBQxEjAQBgN
VBAMTCVNDU0YgVGVzdDCBnzANBgkqhkiG9w0BAQEFAAOBjQAwgYkCgYEA30BboXDe9ITrjAs2D90J4tokUEFhD9qV1cNzRWPywSAmfN5DkhltoiDpHBUB3fBCH2Qj8hRJ9naIhgJspJPtUxMtZcLdQX1tIO4ghQ9Ni+g2V
oBsJ6UWW4/SrGzrMYH0hQuptxUIxE+I3Z/4ol6HTsxMaX747DH+cJFwgFe89LECAwEAAaNJMEcwRQYDVR0BBD4wPIAQHTH8jwqIuYaZiH+H+7YRL6EWMBQxEjAQBgNVBAMTCVNDU0YgVGVzdIIQeL/+xLwYN69BJTCFAOx
F+jAJBgUrDgMCHQUAA4GBACkAUSNs0iB44oDqh/d28RE44vChQJ1rMGjOHqt4cpms6VzkS6h6YJGot9bw6ta42TE6mc7tYxZK8PL9V8qNxDkmTF074ShV8ocYf7xqr656tQo0/EQgDixitVMdAqWJOC6eydRc/MZongS6T
Jj1DytHX7FglaR48ryP4T1rVB+d",
        "provisioningState": "Succeeded",
        "name": "SCSFTest",
        "etag": "W/\"eca6bc41-055a-4702-acfa-1dda7fb10fc3\"",
        "id": "/subscriptions/bfb5e0bf-124b-4d0c-9352-7c0a9f4d9948/resourceGroups/test-trya-group3/providers/Microsoft.Network/applicationGateways/appgw03/sslCertific
ates/SCSFTest"
    }
]
data:    FrontendIpConfigurationText     : [
    {
        "privateIPAllocationMethod": "Dynamic",
        "publicIPAddress": {
            "id": "/subscriptions/bfb5e0bf-124b-4d0c-9352-7c0a9f4d9948/resourceGroups/test-trya-group3/providers/Microsoft.Network/publicIPAddresses/ipforappgateway3"

        },
        "provisioningState": "Succeeded",
        "name": "frontendip03",
        "etag": "W/\"eca6bc41-055a-4702-acfa-1dda7fb10fc3\"",
        "id": "/subscriptions/bfb5e0bf-124b-4d0c-9352-7c0a9f4d9948/resourceGroups/test-trya-group3/providers/Microsoft.Network/applicationGateways/appgw03/frontendIPC
onfigurations/frontendip03"
    }
]
data:    FrontendPortText                : [
    {
        "port": 80,
        "provisioningState": "Succeeded",
        "name": "frontendport03",
        "etag": "W/\"eca6bc41-055a-4702-acfa-1dda7fb10fc3\"",
        "id": "/subscriptions/bfb5e0bf-124b-4d0c-9352-7c0a9f4d9948/resourceGroups/test-trya-group3/providers/Microsoft.Network/applicationGateways/appgw03/frontendPor
ts/frontendport03"
    },
    {
        "port": 3380,
        "provisioningState": "Succeeded",
        "name": "frntport3",
        "etag": "W/\"eca6bc41-055a-4702-acfa-1dda7fb10fc3\"",
        "id": "/subscriptions/bfb5e0bf-124b-4d0c-9352-7c0a9f4d9948/resourceGroups/test-trya-group3/providers/Microsoft.Network/applicationGateways/appgw03/frontendPor
ts/frntport3"
    }
]
data:    BackendAddressPoolText          : [
    {
        "backendAddresses": [
            {
                "ipAddress": "1.1.1.1"
            },
            {
                "ipAddress": "2.2.2.2"
            },
            {
                "ipAddress": "3.3.3.3"
            }
        ],
        "backendIPConfigurations": [],
        "provisioningState": "Succeeded",
        "name": "pool03",
        "etag": "W/\"eca6bc41-055a-4702-acfa-1dda7fb10fc3\"",
        "id": "/subscriptions/bfb5e0bf-124b-4d0c-9352-7c0a9f4d9948/resourceGroups/test-trya-group3/providers/Microsoft.Network/applicationGateways/appgw03/backendAddr
essPools/pool03"
    },
    {
        "backendAddresses": [
            {
                "ipAddress": "4.4.4.4"
            },
            {
                "ipAddress": "5.5.5.5"
            }
        ],
        "backendIPConfigurations": [],
        "provisioningState": "Succeeded",
        "name": "backendpool3",
        "etag": "W/\"eca6bc41-055a-4702-acfa-1dda7fb10fc3\"",
        "id": "/subscriptions/bfb5e0bf-124b-4d0c-9352-7c0a9f4d9948/resourceGroups/test-trya-group3/providers/Microsoft.Network/applicationGateways/appgw03/backendAddr
essPools/backendpool3"
    }
]
data:    BackendHttpSettingsText         : [
    {
        "port": 80,
        "protocol": "Http",
        "cookieBasedAffinity": "Disabled",
        "provisioningState": "Succeeded",
        "name": "setting03",
        "etag": "W/\"eca6bc41-055a-4702-acfa-1dda7fb10fc3\"",
        "id": "/subscriptions/bfb5e0bf-124b-4d0c-9352-7c0a9f4d9948/resourceGroups/test-trya-group3/providers/Microsoft.Network/applicationGateways/appgw03/backendHttp
SettingsCollection/setting03"
    },
    {
        "port": 3380,
        "protocol": "Http",
        "cookieBasedAffinity": "Disabled",
        "provisioningState": "Succeeded",
        "name": "httpsetting3",
        "etag": "W/\"eca6bc41-055a-4702-acfa-1dda7fb10fc3\"",
        "id": "/subscriptions/bfb5e0bf-124b-4d0c-9352-7c0a9f4d9948/resourceGroups/test-trya-group3/providers/Microsoft.Network/applicationGateways/appgw03/backendHttp
SettingsCollection/httpsetting3"
    }
]
data:    HttpListenersText               : [
    {
        "frontendIPConfiguration": {
            "id": "/subscriptions/bfb5e0bf-124b-4d0c-9352-7c0a9f4d9948/resourceGroups/test-trya-group3/providers/Microsoft.Network/applicationGateways/appgw03/fronten
dIPConfigurations/frontendip03"
        },
        "frontendPort": {
            "id": "/subscriptions/bfb5e0bf-124b-4d0c-9352-7c0a9f4d9948/resourceGroups/test-trya-group3/providers/Microsoft.Network/applicationGateways/appgw03/fronten
dPorts/frontendport03"
        },
        "protocol": "Http",
        "provisioningState": "Succeeded",
        "name": "listener03",
        "etag": "W/\"eca6bc41-055a-4702-acfa-1dda7fb10fc3\"",
        "id": "/subscriptions/bfb5e0bf-124b-4d0c-9352-7c0a9f4d9948/resourceGroups/test-trya-group3/providers/Microsoft.Network/applicationGateways/appgw03/httpListene
rs/listener03"
    },
    {
        "frontendIPConfiguration": {
            "id": "/subscriptions/bfb5e0bf-124b-4d0c-9352-7c0a9f4d9948/resourceGroups/test-trya-group3/providers/Microsoft.Network/applicationGateways/appgw03/fronten
dIPConfigurations/frontendip03"
        },
        "frontendPort": {
            "id": "/subscriptions/bfb5e0bf-124b-4d0c-9352-7c0a9f4d9948/resourceGroups/test-trya-group3/providers/Microsoft.Network/applicationGateways/appgw03/fronten
dPorts/frntport3"
        },
        "protocol": "Http",
        "provisioningState": "Succeeded",
        "name": "httplistener3",
        "etag": "W/\"eca6bc41-055a-4702-acfa-1dda7fb10fc3\"",
        "id": "/subscriptions/bfb5e0bf-124b-4d0c-9352-7c0a9f4d9948/resourceGroups/test-trya-group3/providers/Microsoft.Network/applicationGateways/appgw03/httpListene
rs/httplistener3"
    }
]
data:    RequestRoutingRulesText         : [
    {
        "ruleType": "Basic",
        "backendAddressPool": {
            "id": "/subscriptions/bfb5e0bf-124b-4d0c-9352-7c0a9f4d9948/resourceGroups/test-trya-group3/providers/Microsoft.Network/applicationGateways/appgw03/backend
AddressPools/pool03"
        },
        "backendHttpSettings": {
            "id": "/subscriptions/bfb5e0bf-124b-4d0c-9352-7c0a9f4d9948/resourceGroups/test-trya-group3/providers/Microsoft.Network/applicationGateways/appgw03/backend
HttpSettingsCollection/setting03"
        },
        "httpListener": {
            "id": "/subscriptions/bfb5e0bf-124b-4d0c-9352-7c0a9f4d9948/resourceGroups/test-trya-group3/providers/Microsoft.Network/applicationGateways/appgw03/httpLis
teners/listener03"
        },
        "provisioningState": "Succeeded",
        "name": "rule03",
        "etag": "W/\"eca6bc41-055a-4702-acfa-1dda7fb10fc3\"",
        "id": "/subscriptions/bfb5e0bf-124b-4d0c-9352-7c0a9f4d9948/resourceGroups/test-trya-group3/providers/Microsoft.Network/applicationGateways/appgw03/requestRout
ingRules/rule03"
    }
]
data:    Sku                             : {
    "name": "Standard_Small",
    "tier": "Standard",
    "capacity": 6
}
info:    network application-gateway ssl-cert add command OK

</code>
</pre>
