### ISSUE TITLE
ARM:network application-gateway frontend-ip add not working

### ISSUE THREAD

**Issue by sreekanthbs** [MSOpenTech/azure-xplat-cli#517]
1. I provided frontend-ip in command still its prompting for  frontend-ip name

2 Error message is not clear enough

![image](https://cloud.githubusercontent.com/assets/11171941/10165724/560f3124-66de-11e5-9f2b-d29ffb1646ea.png)

**Comment by MikhailTryakhov** [comment]
Thank you, @sreekanthbs 
It's fixed now

**Comment by sreekanthbs** [comment]
@MikhailTryakhov Issue is still there.
I am giving vnet & subnet name , But its giving error for public-ip
![image](https://cloud.githubusercontent.com/assets/11171941/10219187/56e1ef10-685a-11e5-8c40-21c7a9ed5429.png)

**Comment by sreekanthbs** [comment]
@MikhailTryakhov can you please look into this issue

**Comment by MikhailTryakhov** [comment]
@sreekanthbs  I have exactly the same and discuss about it on the meeting

**Comment by MikhailTryakhov** [comment]
Duplicates https://github.com/MSOpenTech/azure-xplat-cli/issues/522
