### ISSUE TITLE
ARM: network express-route peering create and set with Disabled state not working

### ISSUE THREAD

**Issue by sreekanthbs** [MSOpenTech/azure-xplat-cli#555]
network express-route peering create and set with --ms-routing-registry-name RIPE NCC option value not working
![image](https://cloud.githubusercontent.com/assets/11171941/11331483/bec6b45c-91e1-11e5-8909-e350fce80b18.png)

**Comment by MikhailTryakhov** [comment]
Thanks @sreekanthbs, great job!
Fixed now

**Comment by sreekanthbs** [comment]
@MikhailTryakhov still getting error.Please find below the verbose output
<pre>
<code>
C:\Nov\24Nov\3pm\azure-xplat-cli-dev-arm-express-route-peering>node bin/azure network express-route peering create armresgrp24n expressroute1 MicrosoftPeering --vlan-
id 600 --peer-asn 65123  --primary-address-prefix 192.168.1.0/30 --secondary-address-prefix 192.168.2.0/30 -y MicrosoftPeering
info:    Executing command network express-route peering create
+ Looking up the express route circuit "expressroute1"
+ Looking up the express route circuit "expressroute1" peering "MicrosoftPeering"
warn:    Using default peering config: undefined
warn:    Using default peering routing registry name: ARIN
+ Creating express route peering "MicrosoftPeering" in circuit "expressroute1"
+ Looking up the express route circuit "expressroute1" peering "MicrosoftPeering"
data:    Name                            : MicrosoftPeering
data:    Id                              : /subscriptions/bfb5e0bf-124b-4d0c-9352-7c0a9f4d9948/resourceGroups/armresgrp24n/providers/Microsoft.Network/expressRouteCir
cuits/expressroute1/peerings/MicrosoftPeering
data:    Type                            : Microsoft.Network/expressRouteCircuits/peerings
data:    etag                            : W/"af97dfa7-b44b-4037-b36c-7113affda169"
data:    Properties:
data:      Provisioning State            : Failed
data:      Peering Type                  : MicrosoftPeering
data:      Peer ASN                      : 65123
data:      Primary Peer Address Prefix   : 192.168.1.0/30
data:      Secondary Peer Address Prefix : 192.168.2.0/30
data:      State                         : Disabled
data:      Azure ASN                     : 0
data:      Vlan Id                       : 600
data:      Microsoft Peering Config:
data:        Advertised Public Prefixes:
data:        Advertised Public Prefix State: NotConfigured
data:        Customer Asn                : 0
data:        Routing Registry Name       : ARIN
info:    network express-route peering create command OK

C:\Nov\24Nov\3pm\azure-xplat-cli-dev-arm-express-route-peering>node bin/azure network express-route peering set armresgrp24n expressroute1 MicrosoftPeering  --ms-cust
omer-asn 350 --ms-routing-registry-name RIPENCC
info:    Executing command network express-route peering set
+ Looking up the express route circuit "expressroute1"
+ Looking up the express route circuit "expressroute1" peering "MicrosoftPeering"
+ Setting express route peering "MicrosoftPeering" in circuit "expressroute1"
error:   An error occured.
info:    Error information has been recorded to C:\Users\sunil.kumar1\.azure\azure.err
error:   network express-route peering set command failed


C:\Nov\24Nov\3pm\azure-xplat-cli-dev-arm-express-route-peering>node bin/azure network express-route peering set armresgrp24n expressroute1 MicrosoftPeering  --ms-cust
omer-asn 350 --ms-routing-registry-name RIPENCC -vv
info:    Executing command network express-route peering set
verbose: Looking up the express route circuit "expressroute1"
silly:   requestOptions
silly:   {
silly:       rawResponse: false,
silly:       queryString: {},
silly:       method: 'GET',
silly:       headers: { Content-Type: 'application/json' },
silly:       url: 'https://management.azure.com/subscriptions/bfb5e0bf-124b-4d0c-9352-7c0a9f4d9948/resourceGroups/armresgrp24n/providers/Microsoft.Network/expressRout
eCircuits/expressroute1/?api-version=2015-05-01-preview'
silly:   }
silly:   returnObject
silly:   {
silly:       statusCode: 200,
silly:       header: {
silly:           cache-control: 'no-cache',
silly:           pragma: 'no-cache',
silly:           content-length: '1768',
silly:           content-type: 'application/json; charset=utf-8',
silly:           expires: '-1',
silly:           x-ms-request-id: '953d2332-fc8e-4073-a304-f083114ea11b',
silly:           strict-transport-security: 'max-age=31536000; includeSubDomains',
silly:           server: 'Microsoft-HTTPAPI/2.0, Microsoft-HTTPAPI/2.0',
silly:           x-ms-ratelimit-remaining-subscription-reads: '14926',
silly:           x-ms-correlation-request-id: '226a6f5b-b9e7-4331-988b-d98246d75ccd',
silly:           x-ms-routing-request-id: 'WESTINDIA:20151124T094735Z:226a6f5b-b9e7-4331-988b-d98246d75ccd',
silly:           date: 'Tue, 24 Nov 2015 09:47:35 GMT',
silly:           connection: 'close'
silly:       },
silly:       body: '{\015\n  "name": "expressroute1",\015\n  "id": "/subscriptions/bfb5e0bf-124b-4d0c-9352-7c0a9f4d9948/resourceGroups/armresgrp24n/providers/Microsof
t.Network/expressRouteCircuits/expressroute1",\015\n  "etag": "W/\\"af97dfa7-b44b-4037-b36c-7113affda169\\"",\015\n  "type": "Microsoft.Network/expressRouteCircuits",
\015\n  "location": "eastus",\015\n  "properties": {\015\n    "provisioningState": "Failed",\015\n    "resourceGuid": "25a23400-8497-4e09-ad85-aac54b3414b5",\015\n
 "peerings": [\015\n      {\015\n        "name": "MicrosoftPeering",\015\n        "id": "/subscriptions/bfb5e0bf-124b-4d0c-9352-7c0a9f4d9948/resourceGroups/armresgrp2
4n/providers/Microsoft.Network/expressRouteCircuits/expressroute1/peerings/MicrosoftPeering",\015\n        "etag": "W/\\"af97dfa7-b44b-4037-b36c-7113affda169\\"",\015
\n        "properties": {\015\n          "provisioningState": "Failed",\015\n          "peeringType": "MicrosoftPeering",\015\n          "azureASN": 0,\015\n
 "peerASN": 65123,\015\n          "primaryPeerAddressPrefix": "192.168.1.0/30",\015\n          "secondaryPeerAddressPrefix": "192.168.2.0/30",\015\n          "state":
 "Disabled",\015\n          "vlanId": 600,\015\n          "microsoftPeeringConfig": {\015\n            "advertisedPublicPrefixesState": "NotConfigured",\015\n
    "customerASN": 0,\015\n            "routingRegistryName": "ARIN"\015\n          }\015\n        }\015\n      }\015\n    ],\015\n    "authorizations": [],\015\n
"serviceProviderProperties": {\015\n      "serviceProviderName": "InterCloud",\015\n      "peeringLocation": "London",\015\n      "bandwidthInMbps": 100\015\n    },\0
15\n    "circuitProvisioningState": "Enabled",\015\n    "serviceKey": "5ef6924f-854e-49e6-9c2a-4f326a129b28",\015\n    "serviceProviderProvisioningState": "NotProvisi
oned"\015\n  },\015\n  "sku": {\015\n    "name": "Standard_MeteredData",\015\n    "tier": "Standard",\015\n    "family": "MeteredData"\015\n  }\015\n}'
silly:   }
verbose: Looking up the express route circuit "expressroute1" peering "MicrosoftPeering"
silly:   requestOptions
silly:   {
silly:       rawResponse: false,
silly:       queryString: {},
silly:       method: 'GET',
silly:       headers: { Content-Type: 'application/json' },
silly:       url: 'https://management.azure.com/subscriptions/bfb5e0bf-124b-4d0c-9352-7c0a9f4d9948/resourceGroups/armresgrp24n/providers/Microsoft.Network/expressRout
eCircuits/expressroute1/peerings/MicrosoftPeering?api-version=2015-05-01-preview'
silly:   }
silly:   returnObject
silly:   {
silly:       statusCode: 200,
silly:       header: {
silly:           cache-control: 'no-cache',
silly:           pragma: 'no-cache',
silly:           content-length: '725',
silly:           content-type: 'application/json; charset=utf-8',
silly:           expires: '-1',
silly:           x-ms-request-id: '08a49555-79fc-484a-8f29-896a97e45b9f',
silly:           strict-transport-security: 'max-age=31536000; includeSubDomains',
silly:           server: 'Microsoft-HTTPAPI/2.0, Microsoft-HTTPAPI/2.0',
silly:           x-ms-ratelimit-remaining-subscription-reads: '14925',
silly:           x-ms-correlation-request-id: '7b33d2d3-702e-4f8a-a7d0-436fa43cf158',
silly:           x-ms-routing-request-id: 'WESTINDIA:20151124T094737Z:7b33d2d3-702e-4f8a-a7d0-436fa43cf158',
silly:           date: 'Tue, 24 Nov 2015 09:47:37 GMT',
silly:           connection: 'close'
silly:       },
silly:       body: '{\015\n  "name": "MicrosoftPeering",\015\n  "id": "/subscriptions/bfb5e0bf-124b-4d0c-9352-7c0a9f4d9948/resourceGroups/armresgrp24n/providers/Micro
soft.Network/expressRouteCircuits/expressroute1/peerings/MicrosoftPeering",\015\n  "etag": "W/\\"af97dfa7-b44b-4037-b36c-7113affda169\\"",\015\n  "properties": {\015\
n    "provisioningState": "Failed",\015\n    "peeringType": "MicrosoftPeering",\015\n    "azureASN": 0,\015\n    "peerASN": 65123,\015\n    "primaryPeerAddressPrefix"
: "192.168.1.0/30",\015\n    "secondaryPeerAddressPrefix": "192.168.2.0/30",\015\n    "state": "Disabled",\015\n    "vlanId": 600,\015\n    "microsoftPeeringConfig":
{\015\n      "advertisedPublicPrefixesState": "NotConfigured",\015\n      "customerASN": 0,\015\n      "routingRegistryName": "ARIN"\015\n    }\015\n  }\015\n}'
silly:   }
verbose: Setting express route peering "MicrosoftPeering" in circuit "expressroute1"
silly:   requestOptions
silly:   {
silly:       rawResponse: false,
silly:       queryString: {},
silly:       method: 'PUT',
silly:       headers: { Content-Type: 'application/json', Content-Length: 562 },
silly:       url: 'https://management.azure.com/subscriptions/bfb5e0bf-124b-4d0c-9352-7c0a9f4d9948/resourceGroups/armresgrp24n/providers/Microsoft.Network/expressRout
eCircuits/expressroute1/peerings/MicrosoftPeering?api-version=2015-05-01-preview',
silly:       body: '{"properties":{"peeringType":"MicrosoftPeering","state":"Disabled","azureASN":0,"peerASN":65123,"primaryPeerAddressPrefix":"192.168.1.0/30","secon
daryPeerAddressPrefix":"192.168.2.0/30","vlanId":600,"microsoftPeeringConfig":{"customerASN":"350","routingRegistryName":"RIPENCC"},"provisioningState":"Failed"},"nam
e":"MicrosoftPeering","etag":"W/\\"af97dfa7-b44b-4037-b36c-7113affda169\\"","id":"/subscriptions/bfb5e0bf-124b-4d0c-9352-7c0a9f4d9948/resourceGroups/armresgrp24n/prov
iders/Microsoft.Network/expressRouteCircuits/expressroute1/peerings/MicrosoftPeering"}'
silly:   }
silly:   returnObject
silly:   {
silly:       statusCode: 500,
silly:       header: {
silly:           cache-control: 'no-cache',
silly:           pragma: 'no-cache',
silly:           content-length: '115',
silly:           content-type: 'application/json; charset=utf-8',
silly:           expires: '-1',
silly:           x-ms-request-id: '4800a2ab-ebd6-472f-9fca-2d5af3ebdcf5',
silly:           strict-transport-security: 'max-age=31536000; includeSubDomains',
silly:           server: 'Microsoft-HTTPAPI/2.0, Microsoft-HTTPAPI/2.0',
silly:           x-ms-failure-cause: 'service',
silly:           x-ms-ratelimit-remaining-subscription-writes: '1197',
silly:           x-ms-correlation-request-id: '130272f2-c2f8-4244-afac-512a93128888',
silly:           x-ms-routing-request-id: 'WESTINDIA:20151124T094739Z:130272f2-c2f8-4244-afac-512a93128888',
silly:           date: 'Tue, 24 Nov 2015 09:47:38 GMT',
silly:           connection: 'close'
silly:       },
silly:       body: '{\015\n  "error": {\015\n    "code": "InternalServerError",\015\n    "message": "An error occured.",\015\n    "details": []\015\n  }\015\n}'
silly:   }
error:   An error occured.
silly:   {
silly:       stack: 'Error: An error occured.\n    at Function.ServiceClient._normalizeError (C:\\Nov\\24Nov\\3pm\\azure-xplat-cli-dev-arm-express-route-peering\\node
_modules\\azure-common\\lib\\services\\serviceclient.js:815:23)\n    at C:\\Nov\\24Nov\\3pm\\azure-xplat-cli-dev-arm-express-route-peering\\node_modules\\azure-common
\\lib\\services\\filters\\errorhandlingfilter.js:44:29\n    at Request._callback (C:\\Nov\\24Nov\\3pm\\azure-xplat-cli-dev-arm-express-route-peering\\node_modules\\az
ure-common\\lib\\http\\request-pipeline.js:109:14)\n    at Request.self.callback (C:\\Nov\\24Nov\\3pm\\azure-xplat-cli-dev-arm-express-route-peering\\node_modules\\az
ure-common\\node_modules\\request\\request.js:199:22)\n    at Request.emit (events.js:110:17)\n    at Request.<anonymous> (C:\\Nov\\24Nov\\3pm\\azure-xplat-cli-dev-ar
m-express-route-peering\\node_modules\\azure-common\\node_modules\\request\\request.js:1160:14)\n    at Request.emit (events.js:129:20)\n    at IncomingMessage.<anony
mous> (C:\\Nov\\24Nov\\3pm\\azure-xplat-cli-dev-arm-express-route-peering\\node_modules\\azure-common\\node_modules\\request\\request.js:1111:12)\n    at IncomingMess
age.emit (events.js:129:20)\n    at _stream_readable.js:908:16\n',
silly:       message: 'An error occured.',
silly:       code: 'InternalServerError',
silly:       details: [],
silly:       statusCode: 500,
silly:       requestId: '4800a2ab-ebd6-472f-9fca-2d5af3ebdcf5',
silly:       __frame: {
silly:           name: 'setPeering__9',
silly:           line: 244,
silly:           file: 'C:\\Nov\\24Nov\\3pm\\azure-xplat-cli-dev-arm-express-route-peering\\lib\\commands\\arm\\network\\expressRoute._js',
silly:           prev: {
silly:               name: '__111',
silly:               line: 2398,
silly:               file: 'C:\\Nov\\24Nov\\3pm\\azure-xplat-cli-dev-arm-express-route-peering\\lib\\commands\\arm\\network\\network._js',
silly:               prev: undefined,
silly:               calls: 4,
silly:               active: false,
silly:               offset: 7,
silly:               col: 19
silly:           },
silly:           calls: 2,
silly:           active: false,
silly:           offset: 14,
silly:           col: 69
silly:       },
silly:       rawStack: 'Error: An error occured.\n    at Function.ServiceClient._normalizeError (C:\\Nov\\24Nov\\3pm\\azure-xplat-cli-dev-arm-express-route-peering\\n
ode_modules\\azure-common\\lib\\services\\serviceclient.js:815:23)\n    at C:\\Nov\\24Nov\\3pm\\azure-xplat-cli-dev-arm-express-route-peering\\node_modules\\azure-com
mon\\lib\\services\\filters\\errorhandlingfilter.js:44:29\n    at Request._callback (C:\\Nov\\24Nov\\3pm\\azure-xplat-cli-dev-arm-express-route-peering\\node_modules\
\azure-common\\lib\\http\\request-pipeline.js:109:14)\n    at Request.self.callback (C:\\Nov\\24Nov\\3pm\\azure-xplat-cli-dev-arm-express-route-peering\\node_modules\
\azure-common\\node_modules\\request\\request.js:199:22)\n    at Request.emit (events.js:110:17)\n    at Request.<anonymous> (C:\\Nov\\24Nov\\3pm\\azure-xplat-cli-dev
-arm-express-route-peering\\node_modules\\azure-common\\node_modules\\request\\request.js:1160:14)\n    at Request.emit (events.js:129:20)\n    at IncomingMessage.<an
onymous> (C:\\Nov\\24Nov\\3pm\\azure-xplat-cli-dev-arm-express-route-peering\\node_modules\\azure-common\\node_modules\\request\\request.js:1111:12)\n    at IncomingM
essage.emit (events.js:129:20)\n    at _stream_readable.js:908:16\n'
silly:   }
info:    Error information has been recorded to C:\Users\sunil.kumar1\.azure\azure.err
verbose: Error: An error occured.
    at Function.ServiceClient._normalizeError (C:\Nov\24Nov\3pm\azure-xplat-cli-dev-arm-express-route-peering\node_modules\azure-common\lib\services\serviceclient.js:
815:23)
    at C:\Nov\24Nov\3pm\azure-xplat-cli-dev-arm-express-route-peering\node_modules\azure-common\lib\services\filters\errorhandlingfilter.js:44:29
    at Request._callback (C:\Nov\24Nov\3pm\azure-xplat-cli-dev-arm-express-route-peering\node_modules\azure-common\lib\http\request-pipeline.js:109:14)
    at Request.self.callback (C:\Nov\24Nov\3pm\azure-xplat-cli-dev-arm-express-route-peering\node_modules\azure-common\node_modules\request\request.js:199:22)
    at Request.emit (events.js:110:17)
    at Request.<anonymous> (C:\Nov\24Nov\3pm\azure-xplat-cli-dev-arm-express-route-peering\node_modules\azure-common\node_modules\request\request.js:1160:14)
    at Request.emit (events.js:129:20)
    at IncomingMessage.<anonymous> (C:\Nov\24Nov\3pm\azure-xplat-cli-dev-arm-express-route-peering\node_modules\azure-common\node_modules\request\request.js:1111:12)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16

error:   network express-route peering set command failed

</code>
</pre>
